<?php
/**
 * BonjourFencingPolicyApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  PofP\SmartzoneClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Virtual SmartZone - High Scale
 *
 * This reference guide describes the public APIs supported by the Virtual SmartZone - High Scale 6.1.1. Use the RESTful API commands described in this guide as an alternative way to manage the controller and its managed APs (in addition to the web and command line interfaces).
 *
 * The version of the OpenAPI document: v11_1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PofP\SmartzoneClient\Test\Api;

use \PofP\SmartzoneClient\Configuration;
use \PofP\SmartzoneClient\ApiException;
use \PofP\SmartzoneClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BonjourFencingPolicyApiTest Class Doc Comment
 *
 * @category Class
 * @package  PofP\SmartzoneClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BonjourFencingPolicyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addRkszonesBonjourFencingPolicyByZoneId
     *
     * Use this API command to create Bonjour Fencing Policy..
     *
     */
    public function testAddRkszonesBonjourFencingPolicyByZoneId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRkszonesBonjourFencingPolicy
     *
     * Use this API command to delete Bulk Bonjour Fencing Policy..
     *
     */
    public function testDeleteRkszonesBonjourFencingPolicy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRkszonesBonjourFencingPolicyById
     *
     * Use this API command to delete Bonjour Fencing Policy..
     *
     */
    public function testDeleteRkszonesBonjourFencingPolicyById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findApsBonjourFencingStatisticByApMac
     *
     * Use this API command to get Bonjour Fencing Statistic per AP..
     *
     */
    public function testFindApsBonjourFencingStatisticByApMac()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findRkszonesBonjourFencingPolicyById
     *
     * Use this API command to retrieve Bonjour Fencing Policy..
     *
     */
    public function testFindRkszonesBonjourFencingPolicyById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findRkszonesBonjourFencingPolicyByZoneId
     *
     * Use this API command to retrieve a list of Bonjour Fencing Policy..
     *
     */
    public function testFindRkszonesBonjourFencingPolicyByZoneId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findServicesBonjourFencingPolicyByQueryCriteria
     *
     * Use this API command to retrieve a list of Bonjour Fencing Policy..
     *
     */
    public function testFindServicesBonjourFencingPolicyByQueryCriteria()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partialUpdateRkszonesBonjourFencingPolicyById
     *
     * Use this API command to modify the configuration of Bonjour Fencing Policy..
     *
     */
    public function testPartialUpdateRkszonesBonjourFencingPolicyById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
