<?php
/**
 * ClusterManagementApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  PofP\SmartzoneClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Virtual SmartZone - High Scale
 *
 * This reference guide describes the public APIs supported by the Virtual SmartZone - High Scale 6.1.1. Use the RESTful API commands described in this guide as an alternative way to manage the controller and its managed APs (in addition to the web and command line interfaces).
 *
 * The version of the OpenAPI document: v11_1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PofP\SmartzoneClient\Test\Api;

use \PofP\SmartzoneClient\Configuration;
use \PofP\SmartzoneClient\ApiException;
use \PofP\SmartzoneClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ClusterManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  PofP\SmartzoneClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClusterManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addApPatch
     *
     * Use this API command to apply AP patch..
     *
     */
    public function testAddApPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addApPatchFile
     *
     * Use this API command to upload AP Patch File..
     *
     */
    public function testAddApPatchFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addClusterBackup
     *
     * Backup cluster..
     *
     */
    public function testAddClusterBackup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addClusterRestoreById
     *
     * Restore cluster backup by ID..
     *
     */
    public function testAddClusterRestoreById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addConfigurationBackup
     *
     * Backup system configuration..
     *
     */
    public function testAddConfigurationBackup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addConfigurationRestoreById
     *
     * Restore system configuration with specified backupUUID..
     *
     */
    public function testAddConfigurationRestoreById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addConfigurationUpload
     *
     * Upload system configuration file..
     *
     */
    public function testAddConfigurationUpload()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addUpgrade
     *
     * Use this API command to do system upgrade..
     *
     */
    public function testAddUpgrade()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addUpgradeUpload
     *
     * Use this API command to upload patch file..
     *
     */
    public function testAddUpgradeUpload()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteClusterById
     *
     * Delete cluster backup by ID..
     *
     */
    public function testDeleteClusterById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteConfigurationById
     *
     * Delete system configuration file..
     *
     */
    public function testDeleteConfigurationById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findApPatch
     *
     * Use this API command to retrive uploaded AP patch file info..
     *
     */
    public function testFindApPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findApPatchHistory
     *
     * Use this API command to retrive AP patch history..
     *
     */
    public function testFindApPatchHistory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findApPatchStatus
     *
     * Use this API command to retrive cluster progress status..
     *
     */
    public function testFindApPatchStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findCluster
     *
     * Retrive cluster backup list..
     *
     */
    public function testFindCluster()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findClusterGeoRedundancy
     *
     * Get cluster redundancy settings..
     *
     */
    public function testFindClusterGeoRedundancy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findClusterState
     *
     * Use this API command to get current cluster, blade, and management service states.
     *
     */
    public function testFindClusterState()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findConfiguration
     *
     * Retrive system configuration list..
     *
     */
    public function testFindConfiguration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findConfigurationDownload
     *
     * Download system configuration file..
     *
     */
    public function testFindConfigurationDownload()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findConfigurationSettingsAutoExportBackup
     *
     * Get Auto Export Backup Settings..
     *
     */
    public function testFindConfigurationSettingsAutoExportBackup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findConfigurationSettingsScheduleBackup
     *
     * Get Schedule Backup Setting..
     *
     */
    public function testFindConfigurationSettingsScheduleBackup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findUpgradeHistory
     *
     * Use this API command to retrive upgrade history..
     *
     */
    public function testFindUpgradeHistory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findUpgradePatch
     *
     * Use this API command to retrive upload file Info..
     *
     */
    public function testFindUpgradePatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findUpgradeStatus
     *
     * Use this API command to retrive cluster progress status..
     *
     */
    public function testFindUpgradeStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partialUpdateConfigurationSettingsAutoExportBackup
     *
     * Modify Auto Export Backup Settings..
     *
     */
    public function testPartialUpdateConfigurationSettingsAutoExportBackup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partialUpdateConfigurationSettingsScheduleBackup
     *
     * Modify Schedule Backup Setting..
     *
     */
    public function testPartialUpdateConfigurationSettingsScheduleBackup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateClusterGeoRedundancy
     *
     * Update cluster redundancy settings..
     *
     */
    public function testUpdateClusterGeoRedundancy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
