<?php
/**
 * URLFilteringPolicyApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  PofP\SmartzoneClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Virtual SmartZone - High Scale
 *
 * This reference guide describes the public APIs supported by the Virtual SmartZone - High Scale 6.1.1. Use the RESTful API commands described in this guide as an alternative way to manage the controller and its managed APs (in addition to the web and command line interfaces).
 *
 * The version of the OpenAPI document: v11_1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace PofP\SmartzoneClient\Test\Api;

use \PofP\SmartzoneClient\Configuration;
use \PofP\SmartzoneClient\ApiException;
use \PofP\SmartzoneClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * URLFilteringPolicyApiTest Class Doc Comment
 *
 * @category Class
 * @package  PofP\SmartzoneClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class URLFilteringPolicyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addUrlFilteringUrlFilteringPolicy
     *
     * Use this API command to create a URL Filtering policy..
     *
     */
    public function testAddUrlFilteringUrlFilteringPolicy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteUrlFilteringUrlFilteringPolicy
     *
     * Use this API command to delete bulk URL Filtering policies..
     *
     */
    public function testDeleteUrlFilteringUrlFilteringPolicy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteUrlFilteringUrlFilteringPolicyById
     *
     * Use this API command to delete a URL Filtering policy..
     *
     */
    public function testDeleteUrlFilteringUrlFilteringPolicyById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findUrlFilteringBlockCategories
     *
     * Use this API command to retrieve the block categories of URL Filtering..
     *
     */
    public function testFindUrlFilteringBlockCategories()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findUrlFilteringByQueryCriteria
     *
     * Use this API command to retrieve a list of URL Filtering policies by query criteria..
     *
     */
    public function testFindUrlFilteringByQueryCriteria()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findUrlFilteringUrlFilteringPolicy
     *
     * Use this API command to retrieve list of URL Filtering policies..
     *
     */
    public function testFindUrlFilteringUrlFilteringPolicy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findUrlFilteringUrlFilteringPolicyById
     *
     * Use this API command to retrieve an URL Filtering policy..
     *
     */
    public function testFindUrlFilteringUrlFilteringPolicyById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partialUpdateUrlFilteringUrlFilteringPolicyById
     *
     * Use this API command to patch a URL Filtering policy..
     *
     */
    public function testPartialUpdateUrlFilteringUrlFilteringPolicyById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUrlFilteringUrlFilteringPolicyById
     *
     * Use this API command to modify a URL Filtering policy..
     *
     */
    public function testUpdateUrlFilteringUrlFilteringPolicyById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
